<%@ Page Language="C#" EnableEventValidation="false" MasterPageFile="MasterPage.Master" AutoEventWireup="true" CodeBehind="ViewLocations.aspx.cs" Inherits="WebPage.ViewLocations" %>

<asp:Content ID="contentView" runat="server" ContentPlaceHolderID="head">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="idLocationView1" runat="server" AutoGenerateColumns="False" OnRowEditing="EditTable" 
        AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowCancelingEdit="CancelEdit" OnRowDeleting="DeleteRow" 
        OnRowUpdating="UpdateTable" ShowFooter="true" DataKeyNames="id" Width="219px">
        <Columns>
            <%-- <asp:BoundField DataField="location" HeaderText="Operable Locations" />--%>
            
            <asp:TemplateField HeaderText="Operable Locations">
                <ItemTemplate>
                    <asp:Label id="txtLocation1" Text='<%# Bind("location") %>' runat="server" ></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtLocation" Text='<%# Bind("location") %>' runat="server" />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtLocationFooter" runat="server" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField>
                <FooterTemplate>
                    <asp:ImageButton ImageUrl="~/images/addnew.png" runat="server" OnClick="InsertRow" CommandName="Addnew" ToolTip="Addnew" Width="20px" Height="20px" />
                </FooterTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <br />
    <asp:Label ID="lblSuccess" Text="" runat="server" ForeColor="Green" />
    <asp:Label ID="lblFailure" Text="" runat="server" ForeColor="Red" />
</asp:Content>
